if !global.myself.object.taunting
&& !global.myself.object.omnomnomnom
&& !global.myself.object.buffing
&& !global.myself.object.currentWeapon.ubering
&& !global.myself.object.critting
&& !global.myself.object.megaHealed
&& !global.myself.object.stabbing
&& !global.myself.object.carrySentry
&& !global.myself.object.charge
&& !global.myself.object.stunned
    write_ubyte(global.serverSocket, WEAPON_SWAP);
